server:
  port: 8082
  mode: "dev"
redis:
  host: 127.0.0.1
  port: 6381 #6379
  password:
  database: 0
mysql:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123
  dbname: shopdevgo
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifeTime: 3600
logger:
  logLevel: debug
  fileLogName: "./storages/logs/dev.001.log"
  maxSize: 3
  maxBackups: 3
  maxAge: 28
  compress: true
